### ISSUE TITLE
woodworking tables requires 70 unclassified material?

### ISSUE THREAD

**Issue by Daniel-USA** [Adventurer13/ExpandedWoodworkingVGP#1]
i can't build a new woodworking table because the game is asking for 70 of some kind of material. It is a pink square and has no label. The table should only cost iron.

I havent added any mods other than 2 mods that are about traits. it worked when i first started now it's glitched.

**Comment by Adventurer13** [comment]
Just read your comment on steam about it fixing iteself with restarting the game. If it consistently happens again, please attach your output_log, mod config, and a save file I can use to debug.
